[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "karak-game"
version = "0.0.1"
description = "Karak browser game and game engine"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "python-jose",
    "uvicorn",
    "pydantic",
    "PyYAML",
    "jinja2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "karak_shmc*", "shmc_routers*", "shmc_auth_client*"]

[tool.setuptools.package-data]
"app" = [
    "templates/*.html",
    "static/**/*",
    "content/**/*",
]

# python -m pip install --upgrade build
# python -m build
