[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "karak-game"
version = "0.0.3"
description = "Karak browser game and game engine"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "python-jose",
    "shmc-auth-client==0.1.0",
    "uvicorn",
    "pydantic",
    "PyYAML",
    "jinja2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "karak_shmc*", "shmc_routers*"]

[tool.setuptools]
py-modules = ["RUN_API_karak"]

[tool.setuptools.package-data]
"app" = [
    "templates/*.html",
    "static/**/*",
    "content/**/*",
]

# python3 -m pip install --upgrade build
# python3 -m build
